---
title: Blue Olive Group
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Blue Olive description goes here.

'
baseurl: ''
url: http://tingansob.github.io/blueolive
markdown: kramdown
facebook:
  app_id: 
logo: "../css/2016_style/img/icon-large.png"
social:
- title: facebook
  url: https://www.facebook.com
- title: twitter
  url: https://twitter.com
google_site_verification: googleXXXXXXXXXXXXXXXX.html
include:
- _2016_pages
- _2017_pages
plugins:
<<<<<<< HEAD
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
=======
- jekyll-sitemap
- jekyll-seo-tag
>>>>>>> 58643e95800c12ec9152db772a809b69628ac328
permalink: pretty
